
baseURL = "https://yiwuyimei.netlify.app/"
languageCode = "en-us"
title = "Yiwu Yimei Export Products"
theme = "PaperMod"
enableRobotsTXT = true

[params]
  homeInfoParams = { Title = "Yiwu Yimei", Content = "Your trusted exporter of quality Chinese products" }

[[menu.main]]
  identifier = "products"
  name = "Products"
  url = "/products/"
  weight = 1
