
baseURL = "https://yiwuyimei.netlify.app/"
languageCode = "en-us"
title = "Yiwu Yimei Products"
theme = "ananke"
enableRobotsTXT = true

[params]
  description = "Exporting quality products from China to the world."
