baseURL = "https://www.bafangcarton.cn/"
languageCode = "zh-cn"
title = "八方纸箱 - 专业包装解决方案"
theme = "PaperMod"
enableRobotsTXT = true
googleAnalytics = ""

[outputs]
  home = ["HTML", "RSS", "JSON", "SITEMAP"]
  section = ["HTML", "RSS"]
  page = ["HTML"]

[permalinks]
  products = "/products/:slug/"

[params]
  description = "八方纸箱专业提供优质包装纸箱、纸盒定制服务，为客户提供完整的包装解决方案。"
  keywords = ["纸箱", "包装", "纸盒", "定制包装", "工业包装", "物流包装"]
  images = ["/images/og-default.jpg"]

  [params.homeInfoParams]
    Title = "八方纸箱"
    Content = "专业包装解决方案提供商，为您的产品提供安全可靠的包装保护"
    googleFonts = false

[params.assets]
  customCSS = ["css/extra.css","css/service.css","css/packaging.css"]

[[menu.main]]
  identifier = "home"
  name = "首页"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "products"
  name = "产品中心"
  url = "/products/"
  weight = 2

[[menu.main]]
  identifier = "services"
  name = "服务项目"
  url = "/services/"
  weight = 3

[[menu.main]]
  identifier = "about"
  name = "关于我们"
  url = "/about/"
  weight = 4

[[menu.main]]
  identifier = "contact"
  name = "联系我们"
  url = "/contact/"
  weight = 5

